@startuml
collections ECUs
participant SSSF
database "pub/sub endpoint" as pbs
par
ECUs -> SSSF : sample CAN frame
ECUs -->> SSSF: CAN frame
hnote over SSSF
update w_can_block.frames[ind++]
' if receieved frame ID in crititcal
endhnote
alt sizeof(w_can_block.frames) = w_can_block.num_frames
hnote over SSSF
w_can_block.sequence_number++
w_can_block.timestamp = current milliseconds
w_can_block.frame_number = recv_frame_number
w_can_block.need_response = false
endnote
SSSF --> pbs: w_can_block
end
else
SSSF <-- pbs: w_can_block
SSSF -> SSSF: update_network_health()
hnote over SSSF
endhnote 
end
@enduml