@startuml
SSSF ->> Server: Connect
Controller -> Server: Connect
Server -> Controller: Available ECU descriptions
Controller -> Server: Desired network configuration
Server -> SSSF: Multicast endpoint(s)
SSSF -> SSSF: Wait for first CARLA packet,\ntransmit CAN frames
Controller -> Controller: Configure and launch CARLA
Controller -> Controller: Wait for first CARLA packet, \ntransmit CAN frames
@enduml