@startuml
hide methods
    ' title <u>Communication Data Structures</u>

    abstract class COMMBLOCK{
        uint32_t index
        uint32_t frameNumber
        uint64_t timestamp
        {abstract} #uint8_t type
    }

    class WSignalBlock{
        type = 2
        uint8_t num_signals
        float* signals
    }
    COMMBLOCK <|-d- WSignalBlock

    class WCANFrame{
    }
    WCANFrame .|> FlexCAN.CAN_message_t
    WCANFrame .|> FlexCAN.CANFD_message_t
    class WCANBlock{
        type = 1
        uint32_t sequenceNumber
        bool needResponse
        bool fd
    }

    COMMBLOCK <|-r- WCANBlock
    WCANBlock <|-- WCANFrame 
@enduml
