@startuml
skinparam maxmessagesize 40
par
SimulatorLoop <- Controller : sample signals()
SimulatorLoop -->> Controller: sensor signals
hnote over Controller
update w_signal_block.signals
sent_frame_number++
w_signal_block.frame_number = sent_frame_number
endhnote
loop retransmits < max_retransmits and \n sent_frame_number != recv_frame_number
Controller --> SSSF: w_signal_block
SSSF ->> SSSF: process_signal()
SSSF -> SSSF: update_health(...)
Controller -> Controller: Wait for (1000/ (simulator_frame_rate * max_retransmits)) milliseconds
end
hnote over Controller
retransmits = 0
if sent_frame_number != recv_frame_num: 
    lost_simulator_frames++
sent_frame_number = recv_frame_num
endhnote
else
SSSF ->> Controller: w_can_block
hnote over Controller: recv_frame_num = w_can_block.frame_number
end
@enduml